# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/sui/sdx55-sdk-installed/sysroots/x86_64-oesdk-linux/usr/bin/cmake

# The command to remove a file.
RM = /home/sui/sdx55-sdk-installed/sysroots/x86_64-oesdk-linux/usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sui/src/kevin/mqttclient-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sui/src/kevin/mqttclient-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/sui/sdx55-sdk-installed/sysroots/x86_64-oesdk-linux/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/sui/sdx55-sdk-installed/sysroots/x86_64-oesdk-linux/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/sui/sdx55-sdk-installed/sysroots/x86_64-oesdk-linux/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/sui/sdx55-sdk-installed/sysroots/x86_64-oesdk-linux/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/sui/sdx55-sdk-installed/sysroots/x86_64-oesdk-linux/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/sui/sdx55-sdk-installed/sysroots/x86_64-oesdk-linux/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/sui/sdx55-sdk-installed/sysroots/x86_64-oesdk-linux/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/sui/sdx55-sdk-installed/sysroots/x86_64-oesdk-linux/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sui/src/kevin/mqttclient-master/CMakeFiles /home/sui/src/kevin/mqttclient-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sui/src/kevin/mqttclient-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mqtt

# Build rule for target.
mqtt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mqtt
.PHONY : mqtt

# fast build rule for target.
mqtt/fast:
	$(MAKE) -f mqtt/CMakeFiles/mqtt.dir/build.make mqtt/CMakeFiles/mqtt.dir/build
.PHONY : mqtt/fast

#=============================================================================
# Target rules for targets named emqx

# Build rule for target.
emqx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 emqx
.PHONY : emqx

# fast build rule for target.
emqx/fast:
	$(MAKE) -f test/emqx/CMakeFiles/emqx.dir/build.make test/emqx/CMakeFiles/emqx.dir/build
.PHONY : emqx/fast

#=============================================================================
# Target rules for targets named onenet

# Build rule for target.
onenet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 onenet
.PHONY : onenet

# fast build rule for target.
onenet/fast:
	$(MAKE) -f test/onenet/CMakeFiles/onenet.dir/build.make test/onenet/CMakeFiles/onenet.dir/build
.PHONY : onenet/fast

#=============================================================================
# Target rules for targets named baidu

# Build rule for target.
baidu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 baidu
.PHONY : baidu

# fast build rule for target.
baidu/fast:
	$(MAKE) -f test/baidu/CMakeFiles/baidu.dir/build.make test/baidu/CMakeFiles/baidu.dir/build
.PHONY : baidu/fast

#=============================================================================
# Target rules for targets named ali

# Build rule for target.
ali: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ali
.PHONY : ali

# fast build rule for target.
ali/fast:
	$(MAKE) -f test/ali/CMakeFiles/ali.dir/build.make test/ali/CMakeFiles/ali.dir/build
.PHONY : ali/fast

#=============================================================================
# Target rules for targets named platform

# Build rule for target.
platform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 platform
.PHONY : platform

# fast build rule for target.
platform/fast:
	$(MAKE) -f platform/linux/CMakeFiles/platform.dir/build.make platform/linux/CMakeFiles/platform.dir/build
.PHONY : platform/fast

#=============================================================================
# Target rules for targets named network

# Build rule for target.
network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 network
.PHONY : network

# fast build rule for target.
network/fast:
	$(MAKE) -f network/CMakeFiles/network.dir/build.make network/CMakeFiles/network.dir/build
.PHONY : network/fast

#=============================================================================
# Target rules for targets named mbedtls

# Build rule for target.
mbedtls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mbedtls
.PHONY : mbedtls

# fast build rule for target.
mbedtls/fast:
	$(MAKE) -f network/mbedtls/library/CMakeFiles/mbedtls.dir/build.make network/mbedtls/library/CMakeFiles/mbedtls.dir/build
.PHONY : mbedtls/fast

#=============================================================================
# Target rules for targets named wrapper

# Build rule for target.
wrapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wrapper
.PHONY : wrapper

# fast build rule for target.
wrapper/fast:
	$(MAKE) -f network/mbedtls/wrapper/CMakeFiles/wrapper.dir/build.make network/mbedtls/wrapper/CMakeFiles/wrapper.dir/build
.PHONY : wrapper/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f common/CMakeFiles/common.dir/build.make common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named salof

# Build rule for target.
salof: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 salof
.PHONY : salof

# fast build rule for target.
salof/fast:
	$(MAKE) -f common/log/CMakeFiles/salof.dir/build.make common/log/CMakeFiles/salof.dir/build
.PHONY : salof/fast

#=============================================================================
# Target rules for targets named arch

# Build rule for target.
arch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arch
.PHONY : arch

# fast build rule for target.
arch/fast:
	$(MAKE) -f common/log/arch/linux/CMakeFiles/arch.dir/build.make common/log/arch/linux/CMakeFiles/arch.dir/build
.PHONY : arch/fast

#=============================================================================
# Target rules for targets named mqttclient

# Build rule for target.
mqttclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mqttclient
.PHONY : mqttclient

# fast build rule for target.
mqttclient/fast:
	$(MAKE) -f mqttclient/CMakeFiles/mqttclient.dir/build.make mqttclient/CMakeFiles/mqttclient.dir/build
.PHONY : mqttclient/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mqtt"
	@echo "... emqx"
	@echo "... onenet"
	@echo "... baidu"
	@echo "... ali"
	@echo "... platform"
	@echo "... network"
	@echo "... mbedtls"
	@echo "... wrapper"
	@echo "... common"
	@echo "... salof"
	@echo "... arch"
	@echo "... mqttclient"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

